name: pypi package ncm api

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # specify the version of Python you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine build

    - name: Build package
      run: cd ncm && python -m build --sdist --wheel

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # make sure you have set up the secret in your repository settings
      run: |
        cd ncm && twine upload dist/*