name: bump version

on:
  push:
    paths:
      - "ncm/**"

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # specify the version of Python you're using

      - name: Bump version
        run: |
          cd ncm && bump2version patch

      - name: Push changes
        run: |
          git push origin main
