name: bump version

on:
  push:
    paths:
      - "ncm/**"

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # specify the version of Python you're using
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version
          git config --global user.email "github_action@example.com"
          git config --global user.name "Github Action"
      - name: Bump version
        run: |
          cd ncm && bump2version patch
      - name: Push changes
        run: |
          git push origin master && git push origin master --tags
